#services:
#
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-container
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: role_task_manager
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#
#  app:
#    image: role-based-task-manager:1.0
#    container_name: springboot-container
#    depends_on:
#      - mysql
#    ports:
#      - "8081:8081"
#
#volumes:
#  mysql-data:


services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: role_task_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: role-based-task-manager:1.0
    container_name: springboot-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/role_task_manager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8081"

volumes:
  mysql-data: